app = "secret-hitler-backend"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80

# Uncomment if persistent storage is needed later
# [[mounts]]
#   source = "data"
#   destination = "/data"
